'use strict';


var ErrorCode = {
	UNKNOWN_ERROR: 1,
	
	DB_UNKNOWN_ERROR: 100,

	USER_UNKNOWN_ERROR: 200,
	USER_NAME_ALREADY_USED: 201,
	USER_EMAIL_ALREADY_USED: 202,
	USER_NOT_FOUND: 203,

	DEVICE_UNKNOWN_ERROR: 300,
	DEVICE_NOT_FOUND: 301,

	HARDWARE_UNKNOWN_ERROR: 400,

	REQUEST_UNKNOWN_ERROR: 500,
	REQUEST_PARAMETER_INVALID: 501	
}


module.exports = {
	ErrorCode: ErrorCode
}
